on:
    issues:
        types: [labeled]
jobs:
    move_priority_design_issues:
        name: Move priority X-Needs-Design issues to Design project board
        runs-on: ubuntu-latest
        if: >
            contains(github.event.issue.labels.*.name, 'X-Needs-Design') &&
             (contains(github.event.issue.labels.*.name, 'O-Frequent') ||
              contains(github.event.issue.labels.*.name, 'O-Occasional')) &&
             (contains(github.event.issue.labels.*.name, 'S-Critical') ||
              contains(github.event.issue.labels.*.name, 'S-Major') ||
              contains(github.event.issue.labels.*.name, 'S-Minor'))
        steps:
             - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
               with:
                 action-token: "${{ secrets.ELEMENT_BOT_TOKEN }}"
                 project-url: "https://github.com/orgs/vector-im/projects/14"
                 column-name: "📥 Inbox"
                 label-name: "X-Needs-Design"

    move_spaces_issues:
        name: Move Spaces issues to Delight project board
        runs-on: ubuntu-latest
        if: >
            contains(github.event.issue.labels.*.name, 'A-Spaces') ||
            contains(github.event.issue.labels.*.name, 'A-Space-Settings') ||
            contains(github.event.issue.labels.*.name, 'A-Subspaces')
        steps:
             - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
               with:
                 action-token: "${{ secrets.ELEMENT_BOT_TOKEN }}"
                 project-url: "https://github.com/orgs/vector-im/projects/6"
                 column-name: "📥 Inbox"
                 label-name: "A-Spaces"
