name: Move P1 bugs to boards

on:
  issues:
    types: [labeled, unlabeled]

jobs:
  P1_issues_to_crypto_team_workboard:
    runs-on: ubuntu-latest
    if: >
      contains(github.event.issue.labels.*.name, 'Z-UISI') ||
      (contains(github.event.issue.labels.*.name, 'A-E2EE') ||
       contains(github.event.issue.labels.*.name, 'A-E2EE-Cross-Signing') ||
       contains(github.event.issue.labels.*.name, 'A-E2EE-Dehydration') ||
       contains(github.event.issue.labels.*.name, 'A-E2EE-Key-Backup') ||
       contains(github.event.issue.labels.*.name, 'A-E2EE-SAS-Verification')) &&
      (contains(github.event.issue.labels.*.name, 'T-Defect') &&
       contains(github.event.issue.labels.*.name, 'S-Critical') &&
       (contains(github.event.issue.labels.*.name, 'O-Frequent') ||
        contains(github.event.issue.labels.*.name, 'O-Occasional')) ||
       contains(github.event.issue.labels.*.name, 'S-Major') &&
       contains(github.event.issue.labels.*.name, 'O-Frequent') ||
       contains(github.event.issue.labels.*.name, 'A11y') &&
       contains(github.event.issue.labels.*.name, 'O-Frequent'))
    steps:
      - uses: alex-page/github-project-automation-plus@be108970955040d35dd6d053c3aff3faaf678026
        with:
          project: Crypto Team
          column: Ready
          repo-token: ${{ secrets.ELEMENT_BOT_TOKEN }}
