name: Move issued assigned to specific team members to their boards

on:
    issues:
        types: [assigned]

jobs:
    web-app-team:
        runs-on: ubuntu-latest
        if: |
            contains(github.event.issue.assignees.*.login, 't3chguy') ||
            contains(github.event.issue.assignees.*.login, 'andybalaam') ||
            contains(github.event.issue.assignees.*.login, 'justjanne')
        steps:
            - uses: actions/add-to-project@main
              with:
                  project-url: https://github.com/orgs/vector-im/projects/67
                  github-token: ${{ secrets.ELEMENT_BOT_TOKEN }}
