name: Deploy to GitHub Pages

env:
  # Whether to deploy the conference interface (`up`) or off-season placeholder message (`down`)
  MODE: down

on:
  push: { branches: [2025] }
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - run: |
          docker build \
            --build-arg 'MODE' \
            --file 'Containerfile' \
            --output 'type=local,dest=github-pages' \
            --target 'static-site' \
            .

      - uses: actions/upload-pages-artifact@v5
        with: { path: github-pages }

  github_pages:
    permissions: { id-token: write, pages: write }
    environment: { name: github-pages, url: "${{ steps.deploy.outputs.page_url }}" }
    concurrency: { group: github-pages, cancel-in-progress: true }

    needs: build
    runs-on: ubuntu-slim
    steps:
      - id: deploy
        uses: actions/deploy-pages@v5
