name: Dockerhub
on:
    workflow_dispatch: {}
    push:
        tags: [v*]
    schedule:
        # This job can take a while, and we have usage limits, so just publish develop only twice a day
        - cron: "0 7/12 * * *"
concurrency: ${{ github.workflow }}-${{ github.ref_name }}
jobs:
    buildx:
        name: Docker Buildx
        runs-on: ubuntu-latest
        environment: dockerhub
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # needed for docker-package to be able to calculate the version

            - name: Set up QEMU
              uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2
              with:
                  install: true

            - name: Login to Docker Hub
              uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175 # v4
              with:
                  images: |
                      vectorim/element-web
                  tags: |
                      type=ref,event=branch
                      type=ref,event=tag
                  flavor: |
                      latest=${{ contains(github.ref_name, '-rc.') && 'false' || 'auto' }}

            - name: Build and push
              uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # v4
              with:
                  context: .
                  push: true
                  platforms: linux/amd64,linux/arm64
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}

            - name: Update repo description
              uses: peter-evans/dockerhub-description@dc67fad7001ef9e8e3c124cb7a64e16d0a63d864 # v3
              continue-on-error: true
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
                  repository: vectorim/element-web
